In [106]:
#imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sqlalchemy import create_engine
engine = create_engine('sqlite:///data/wildfires.sqlite')

In [107]:
#Read in CSV
df = pd.read_csv('data/FW_Veg_Rem_Combined.csv')

df.head()

,Unnamed: 0.1,Unnamed: 0,fire_name,fire_size,fire_size_class,stat_cause_descr,latitude,longitude,state,disc_clean_date,...,Wind_cont,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness
0,0,0,NaN,10.0,C,Missing/Undefined,18.105072,-66.753044,PR,2/11/2007,...,3.250413,78.216590,76.793750,76.381579,78.724370,0.0,0.0,0.0,0.0,0.017923
1,1,1,NaN,3.0,B,Arson,35.038330,-87.610000,TN,12/11/2006,...,2.122320,70.840000,65.858911,55.505882,81.682678,59.8,8.4,0.0,86.8,0.184355
2,2,2,NaN,60.0,C,Arson,34.947800,-88.722500,MS,2/29/2004,...,3.369050,75.531629,75.868613,76.812834,65.063800,168.8,42.2,18.1,124.5,0.194544
3,3,3,WNA 1,1.0,B,Debris Burning,39.641400,-119.308300,NV,6/6/2005,...,0.000000,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447
4,4,4,NaN,2.0,B,Miscellaneous,30.700600,-90.591400,LA,9/22/1999,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.214633

In [108]:
#Read datatypes of CSV
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55367 entries, 0 to 55366
Data columns (total 43 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0.1      55367 non-null  int64
 1   Unnamed: 0        55367 non-null  int64
 2   fire_name         25913 non-null  object
 3   fire_size         55367 non-null  float64
 4   fire_size_class   55367 non-null  object
 5   stat_cause_descr  55367 non-null  object
 6   latitude          55367 non-null  float64
 7   longitude         55367 non-null  float64
 8   state             55367 non-null  object
 9   disc_clean_date   55367 non-null  object
 10  cont_clean_date   27477 non-null  object
 11  discovery_month   55367 non-null  object
 12  disc_date_final   28708 non-null  object
 13  cont_date_final   25632 non-null  object
 14  putout_time       27477 non-null  object
 15  disc_date_pre     55367 non-null  object
 16  disc_pre_year     55367 non-null  int64
 17  disc_pre_month    55367 non-null  object
 18  wstation_usaf     55367 non-null  object
 19  dstation_m        55367 non-null  float64
 20  wstation_wban     55367 non-null  int64
 21  wstation_byear    55367 non-null  int64
 22  wstation_eyear    55367 non-null  int64
 23  Vegetation        55367 non-null  int64
 24  fire_mag          55367 non-null  float64
 25  weather_file      55367 non-null  object
 26  Temp_pre_30       55367 non-null  float64
 27  Temp_pre_15       55367 non-null  float64
 28  Temp_pre_7        55367 non-null  float64
 29  Temp_cont         55367 non-null  float64
 30  Wind_pre_30       55367 non-null  float64
 31  Wind_pre_15       55367 non-null  float64
 32  Wind_pre_7        55367 non-null  float64
 33  Wind_cont         55367 non-null  float64
 34  Hum_pre_30        55367 non-null  float64
 35  Hum_pre_15        55367 non-null  float64
 36  Hum_pre_7         55367 non-null  float64
 37  Hum_cont          55367 non-null  float64
 38  Prec_pre_30       55367 non-null  float64
 39  Prec_pre_15       55367 non-null  float64
 40  Prec_pre_7        55367 non-null  float64
 41  Prec_cont         55367 non-null  float64
 42  remoteness        55367 non-null  float64
dtypes: float64(22), int64(7), object(14)
memory usage: 18.2+ MB

In [109]:
#Drop unneeded columns
df = df.drop(['Unnamed: 0.1','Unnamed: 0','disc_date_pre','disc_pre_year','disc_pre_month','wstation_usaf','dstation_m','wstation_wban','wstation_byear','wstation_eyear','weather_file','putout_time','cont_clean_date','disc_date_final','cont_date_final'], axis=1)

In [110]:
#Eliminate null climate data
df2 = df[df.Temp_pre_30 != -1]

df2 =df2.reset_index(drop=True)
df2.head()

,fire_name,fire_size,fire_size_class,stat_cause_descr,latitude,longitude,state,disc_clean_date,discovery_month,Vegetation,...,Wind_cont,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness
0,NaN,10.0,C,Missing/Undefined,18.105072,-66.753044,PR,2/11/2007,Feb,12,...,3.250413,78.216590,76.793750,76.381579,78.724370,0.0,0.0,0.0,0.0,0.017923
1,NaN,3.0,B,Arson,35.038330,-87.610000,TN,12/11/2006,Dec,15,...,2.122320,70.840000,65.858911,55.505882,81.682678,59.8,8.4,0.0,86.8,0.184355
2,NaN,60.0,C,Arson,34.947800,-88.722500,MS,2/29/2004,Feb,16,...,3.369050,75.531629,75.868613,76.812834,65.063800,168.8,42.2,18.1,124.5,0.194544
3,WNA 1,1.0,B,Debris Burning,39.641400,-119.308300,NV,6/6/2005,Jun,0,...,0.000000,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447
4,NaN,5.2,B,Debris Burning,31.316978,-83.393649,GA,1/10/2009,Jan,12,...,0.000000,79.896679,73.431818,0.000000,0.000000,26.0,0.0,0.0,0.0,0.148904

In [111]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41132 entries, 0 to 41131
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fire_name         20450 non-null  object
 1   fire_size         41132 non-null  float64
 2   fire_size_class   41132 non-null  object
 3   stat_cause_descr  41132 non-null  object
 4   latitude          41132 non-null  float64
 5   longitude         41132 non-null  float64
 6   state             41132 non-null  object
 7   disc_clean_date   41132 non-null  object
 8   discovery_month   41132 non-null  object
 9   Vegetation        41132 non-null  int64
 10  fire_mag          41132 non-null  float64
 11  Temp_pre_30       41132 non-null  float64
 12  Temp_pre_15       41132 non-null  float64
 13  Temp_pre_7        41132 non-null  float64
 14  Temp_cont         41132 non-null  float64
 15  Wind_pre_30       41132 non-null  float64
 16  Wind_pre_15       41132 non-null  float64
 17  Wind_pre_7        41132 non-null  float64
 18  Wind_cont         41132 non-null  float64
 19  Hum_pre_30        41132 non-null  float64
 20  Hum_pre_15        41132 non-null  float64
 21  Hum_pre_7         41132 non-null  float64
 22  Hum_cont          41132 non-null  float64
 23  Prec_pre_30       41132 non-null  float64
 24  Prec_pre_15       41132 non-null  float64
 25  Prec_pre_7        41132 non-null  float64
 26  Prec_cont         41132 non-null  float64
 27  remoteness        41132 non-null  float64
dtypes: float64(21), int64(1), object(6)
memory usage: 8.8+ MB

In [112]:
#Only grab named fires
df3 = df2[df2.fire_name.notnull()]

df3

,fire_name,fire_size,fire_size_class,stat_cause_descr,latitude,longitude,state,disc_clean_date,discovery_month,Vegetation,...,Wind_cont,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness
3,WNA 1,1.0,B,Debris Burning,39.641400,-119.308300,NV,6/6/2005,Jun,0,...,0.000000,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447
7,CRAZY,1.0,B,Miscellaneous,48.839400,-99.718500,ND,4/19/2004,Apr,15,...,0.000000,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683
11,ROLSTON,1.0,B,Missing/Undefined,33.988609,-103.135277,NM,2/12/1996,Feb,16,...,6.062726,38.712707,45.180055,40.493976,33.537604,10.0,8.0,0.0,0.0,0.330323
14,TELEPHONE FIRE,5.0,B,Debris Burning,33.779575,-96.025915,TX,12/18/2010,Dec,16,...,4.461400,62.304326,60.116883,53.782222,70.162664,0.0,0.0,0.0,0.0,0.262885
17,STO3573155,2.0,B,Debris Burning,35.718900,-92.335000,AR,1/19/2014,Jan,15,...,0.000000,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41127,LILLIAM RANCH,3500.0,F,Missing/Undefined,37.606667,-96.422500,KS,2/12/2015,Feb,0,...,4.559206,62.971774,69.376658,68.118919,64.008028,20.1,18.8,0.0,3.8,0.365622
41128,GUTTERSEN RANCH,11699.0,G,Missing/Undefined,40.394700,-104.564600,CO,9/18/2015,Sep,14,...,2.744039,51.010341,50.264501,48.204861,57.236620,4.6,0.0,0.0,4.8,0.199532
41129,IMPACT,6289.0,G,Missing/Undefined,39.180000,-96.784167,KS,10/15/2015,Oct,0,...,3.804803,65.671410,61.839572,54.625698,55.042092,35.4,8.2,0.0,249.0,0.331501
41130,WILLOW,5702.0,G,Arson,37.262607,-119.511139,CA,7/25/2015,Jul,0,...,2.529158,43.755556,43.755556,44.443975,35.924406,0.0,0.0,0.0,0.0,0.097682
41131,VALLEY,76067.0,G,Missing/Undefined,38.843988,-122.759707,CA,9/12/2015,Sep,0,...,1.208073,50.521912,46.310627,37.178571,58.063802,0.3,0.3,0.0,18.8,0.167305

In [113]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20450 entries, 3 to 41131
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fire_name         20450 non-null  object
 1   fire_size         20450 non-null  float64
 2   fire_size_class   20450 non-null  object
 3   stat_cause_descr  20450 non-null  object
 4   latitude          20450 non-null  float64
 5   longitude         20450 non-null  float64
 6   state             20450 non-null  object
 7   disc_clean_date   20450 non-null  object
 8   discovery_month   20450 non-null  object
 9   Vegetation        20450 non-null  int64
 10  fire_mag          20450 non-null  float64
 11  Temp_pre_30       20450 non-null  float64
 12  Temp_pre_15       20450 non-null  float64
 13  Temp_pre_7        20450 non-null  float64
 14  Temp_cont         20450 non-null  float64
 15  Wind_pre_30       20450 non-null  float64
 16  Wind_pre_15       20450 non-null  float64
 17  Wind_pre_7        20450 non-null  float64
 18  Wind_cont         20450 non-null  float64
 19  Hum_pre_30        20450 non-null  float64
 20  Hum_pre_15        20450 non-null  float64
 21  Hum_pre_7         20450 non-null  float64
 22  Hum_cont          20450 non-null  float64
 23  Prec_pre_30       20450 non-null  float64
 24  Prec_pre_15       20450 non-null  float64
 25  Prec_pre_7        20450 non-null  float64
 26  Prec_cont         20450 non-null  float64
 27  remoteness        20450 non-null  float64
dtypes: float64(21), int64(1), object(6)
memory usage: 4.5+ MB

In [114]:
df3.stat_cause_descr.value_counts()

Lightning            5280
Debris Burning       4074
Miscellaneous        3477
Arson                2359
Equipment Use        1799
Missing/Undefined    1384
Campfire              544
Children              467
Powerline             352
Smoking               351
Railroad              168
Fireworks             154
Structure              41
Name: stat_cause_descr, dtype: int64

In [115]:
print(df3.fire_size_class.value_counts())

B    11214
C     3488
G     3135
F     1486
D      687
E      440
Name: fire_size_class, dtype: int64

In [116]:
print(df3.Temp_pre_7)

3        18.142564
7         6.053333
11        8.913095
14        6.558045
17        0.000000
           ...
41127     4.437563
41128    18.678201
41129    18.918994
41130    28.166667
41131    21.963095
Name: Temp_pre_7, Length: 20450, dtype: float64

In [117]:
#Write data to a sqlite db
df3.to_sql('wildfires', con=engine,if_exists='replace',index=False)

20450